FROM python:3.11-slim

WORKDIR /app/streamlit_app
COPY streamlit_app/requirements.txt /app/streamlit_app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# project code mounted in dev; in prod copy your code
