# Generated by Django 5.2.9 on 2026-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=128, unique=True)),
                ('schedule_mode', models.CharField(max_length=64)),
                ('mapping_table', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_schedule_config',
            },
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=32, unique=True)),
                ('schedule_name', models.CharField(max_length=128)),
                ('schedule_mode', models.CharField(blank=True, default='', max_length=64)),
                ('mapping_table', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('NG', 'NG')], max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_schedule_log',
                'indexes': [models.Index(fields=['schedule_name', 'created_at'], name='tb_schedule_schedul_087e14_idx'), models.Index(fields=['status', 'created_at'], name='tb_schedule_status_f85022_idx')],
            },
        ),
    ]
