# Generated by Django 5.2.9 on 2026-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='config_json',
        ),
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='retry_backoff_ms',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='retry_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='schedule_opt',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='schedule_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='status',
            field=models.CharField(default='ENABLED', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='timeout_ms',
            field=models.IntegerField(default=15000),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='mapping_table',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='schedule_mode',
            field=models.CharField(default='API', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='schedule_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='scheduleconfig',
            table='tb_schedule_configs',
        ),
    ]
